language: php 

php:
  - 7.2
notifications:
  email: false

install:
  - composer install --prefer-dist --verbose

script:
  - ./vendor/bin/phpcs ./
      --standard=ruleset.xml
      --ignore="cfx/*,vendor/*"
      --colors
      --extensions=php,js,css